import { createClient } from "@/lib/supabase/server";
import { getCurrentUser } from "@/lib/db/queries";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/layout/page-header";
import type { BriefDraft } from "@/lib/types/pipeline";

export default async function BriefsPage() {
  const supabase = await createClient();
  const user = await getCurrentUser(supabase);
  if (!user) return null;

  const { data: briefs } = await supabase
    .from("briefs")
    .select("*, clients(name)")
    .order("created_at", { ascending: false });

  return (
    <div className="space-y-6">
      <PageHeader
        title="Briefs"
        description="Designer-ready briefs generated by AI or created manually."
      />

      {(briefs ?? []).length === 0 ? (
        <p className="text-muted-foreground">No briefs yet. Approve an Inbox AI item to create one.</p>
      ) : (
        <div className="grid gap-4">
          {(briefs ?? []).map((b: {
            id: string;
            content: BriefDraft;
            status: string;
            created_by_ai: boolean;
            created_at: string;
            clients: { name: string };
          }) => (
            <Card key={b.id} className="stripe-card border-0 ring-0">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="text-base">
                    {(b.content as BriefDraft)?.deliverable || "Brief"}
                  </CardTitle>
                  <div className="flex gap-2">
                    <Badge variant="outline">{b.status}</Badge>
                    {b.created_by_ai && <Badge>AI</Badge>}
                  </div>
                </div>
                <p className="text-sm text-muted-foreground">{b.clients?.name}</p>
              </CardHeader>
              <CardContent className="text-sm text-muted-foreground">
                <p>{(b.content as BriefDraft)?.objective}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
